"""
Export research results to Markdown and HTML formats.

Usage:
    from utils.exporter import to_markdown, to_html

    md = to_markdown("quantum computing", result_data)
    html = to_html("quantum computing", result_data)
"""

import html as html_module
from datetime import datetime
from typing import Any

import logging

logger = logging.getLogger(__name__)


def to_markdown(topic: str, result_data: dict[str, Any]) -> str:
    """Convert a cached research result dict into clean Markdown.

    Expected keys in *result_data* (all optional, degrades gracefully):
        - answer / data:  The main research text.
        - sources:        List of ``{url, title, reliability_score}``.
        - status:         e.g. "success".
    """
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines: list[str] = []
    lines.append(f"# Deep Research: {topic}")
    lines.append("")
    lines.append(f"**Exported:** {now}")
    lines.append("")
    lines.append("---")
    lines.append("")

    # --- Main findings ---
    answer = result_data.get("answer") or result_data.get("data") or ""
    if answer:
        lines.append("## Findings")
        lines.append("")
        lines.append(str(answer))
        lines.append("")

    # --- Sources ---
    sources = result_data.get("sources", [])
    if sources:
        lines.append("## Sources")
        lines.append("")
        for src in sources:
            title = src.get("title", "Untitled")
            url = src.get("url", "")
            score = src.get("reliability_score")
            score_str = f" (reliability: {score}/100)" if score is not None else ""
            if url:
                lines.append(f"- [{title}]({url}){score_str}")
            else:
                lines.append(f"- {title}{score_str}")
        lines.append("")

    # --- Conclusion ---
    conclusion = result_data.get("conclusion", "")
    if conclusion:
        lines.append("## Conclusion")
        lines.append("")
        lines.append(str(conclusion))
        lines.append("")

    # --- Status footer ---
    status = result_data.get("status", "")
    if status:
        lines.append("---")
        lines.append("")
        lines.append(f"*Research status: {status}*")
        lines.append("")

    return "\n".join(lines)


def to_html(topic: str, result_data: dict[str, Any]) -> str:
    """Wrap the Markdown export in a minimal, self-contained HTML page."""
    md_content = to_markdown(topic, result_data)

    # Simple Markdown-to-HTML conversion (no external dependency)
    body_html = _simple_md_to_html(md_content)
    safe_title = html_module.escape(topic)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Research: {safe_title}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            max-width: 820px;
            margin: 2rem auto;
            padding: 0 1rem;
            line-height: 1.6;
            color: #1a1a1a;
            background: #fafafa;
        }}
        h1 {{ border-bottom: 2px solid #333; padding-bottom: 0.3em; }}
        h2 {{ color: #2c3e50; margin-top: 1.8em; }}
        a {{ color: #2980b9; text-decoration: none; }}
        a:hover {{ text-decoration: underline; }}
        hr {{ border: none; border-top: 1px solid #ddd; margin: 1.5em 0; }}
        ul {{ padding-left: 1.5em; }}
        code {{ background: #f0f0f0; padding: 0.1em 0.3em; border-radius: 3px; }}
        pre {{ background: #f0f0f0; padding: 1em; border-radius: 5px; overflow-x: auto; }}
        .footer {{ margin-top: 3em; font-size: 0.85em; color: #888; text-align: center; }}
    </style>
</head>
<body>
{body_html}
<div class="footer">
    Generated by LocoDex Deep Search v1.1
</div>
</body>
</html>"""


def _simple_md_to_html(md: str) -> str:
    """Minimal Markdown to HTML (no dependency).

    Handles: headings, bold, italic, links, unordered lists, horizontal
    rules, code blocks, and paragraphs.  Good enough for structured
    research output.
    """
    import re

    html_lines: list[str] = []
    in_list = False
    in_code_block = False

    for line in md.split("\n"):
        stripped = line.strip()

        # Fenced code blocks
        if stripped.startswith("```"):
            if in_code_block:
                html_lines.append("</code></pre>")
                in_code_block = False
            else:
                html_lines.append("<pre><code>")
                in_code_block = True
            continue
        if in_code_block:
            html_lines.append(html_module.escape(line))
            continue

        # Close list if we're no longer in one
        if in_list and not stripped.startswith("- "):
            html_lines.append("</ul>")
            in_list = False

        # Horizontal rule
        if stripped in ("---", "***", "___"):
            html_lines.append("<hr>")
            continue

        # Headings
        if stripped.startswith("# "):
            html_lines.append(f"<h1>{_inline(stripped[2:])}</h1>")
            continue
        if stripped.startswith("## "):
            html_lines.append(f"<h2>{_inline(stripped[3:])}</h2>")
            continue
        if stripped.startswith("### "):
            html_lines.append(f"<h3>{_inline(stripped[4:])}</h3>")
            continue

        # Unordered list
        if stripped.startswith("- "):
            if not in_list:
                html_lines.append("<ul>")
                in_list = True
            html_lines.append(f"<li>{_inline(stripped[2:])}</li>")
            continue

        # Empty line
        if not stripped:
            html_lines.append("")
            continue

        # Paragraph
        html_lines.append(f"<p>{_inline(stripped)}</p>")

    if in_list:
        html_lines.append("</ul>")
    if in_code_block:
        html_lines.append("</code></pre>")

    return "\n".join(html_lines)


def _inline(text: str) -> str:
    """Process inline Markdown: bold, italic, links, inline code."""
    import re

    # Escape HTML entities first
    text = html_module.escape(text)

    # Inline code (`...`)
    text = re.sub(r"`([^`]+)`", r"<code>\1</code>", text)
    # Bold (**...**)
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    # Italic (*...*)
    text = re.sub(r"\*(.+?)\*", r"<em>\1</em>", text)
    # Links [text](url)
    text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2">\1</a>', text)

    return text
